name: malhaeboredo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.2
  flutter_native_splash: ^2.4.4
  fluttertoast: ^8.2.12
  flutter_web_frame: ^1.0.0
  youtube_player_flutter: ^9.1.1
  kakao_flutter_sdk: ^1.9.6
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  dio: ^5.8.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/images/Onboarding_image_1.png
      - assets/images/Onboarding_image_2.png
      - assets/images/Onboarding_image_3.png
      - assets/images/Onboarding_image_4.png
      - assets/images/Onboarding_image_5.png
      - assets/images/Onboarding_image_6.png
      - assets/images/Home_image.png
      - assets/images/Writing_image.png
      - assets/images/Throw_bottle.gif
      - assets/images/Throw_reply.gif
      - assets/images/bottle.png
      - assets/images/background_image.png
      - assets/images/Throw_away.gif
      - assets/images/paper.png
      - assets/images/Splash.png
      - assets/images/full_bottle.png
      - assets/images/paper1.png
      - assets/images/comment.png
      - assets/images/Mypage_image.png
      - assets/images/box.png
      - assets/images/arrow.png
      - assets/images/Bear.png
      - assets/images/PaperBlue.png
      - assets/images/PaperPink.png
      - assets/images/Profile_bird.png
      - assets/images/Profile_daram.png
      - assets/images/Profile_gom.png
      - assets/images/Profile_pen.png
      - assets/images/Logo.png
      - assets/images/Subtitle.png
      - assets/images/KakaoLogin.png
      - assets/images/UserCircle.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Moneygraphy
       fonts:
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 100
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 200
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 300
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 400
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 500
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 600
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 700
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 800
        - asset: assets/fonts/Moneygraphy-Pixel.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
